wandb_version: 1

project:
  desc: null
  value: hmrl
name:
  desc: null
  value: ppo-b485-seed:1
task:
  desc: null
  value: MetaGym-ML10
algo_name:
  desc: null
  value: ppo
group:
  desc: null
  value: MetaGym-ML10-ppo-b485
logdir:
  desc: null
  value: log/MetaGym-ML10-ppo-b485
log_interval:
  desc: null
  value: 10
env_type:
  desc: null
  value: MetaGym
agent_type:
  desc: null
  value: ML10
task_name:
  desc: null
  value: null
task_num:
  desc: null
  value: null
seeds:
  desc: null
  value:
  - 1
  - 3
  - 5
  - 7
  - 9
num_cores:
  desc: null
  value: null
actor_hidden_dims:
  desc: null
  value:
  - 256
  - 256
hidden_dims:
  desc: null
  value:
  - 256
  - 256
K_epochs:
  desc: null
  value: 5
eps_clip:
  desc: null
  value: 0.1
actor_lr:
  desc: null
  value: 0.0003
critic_lr:
  desc: null
  value: 0.0007
encoder_lr:
  desc: null
  value: 0.0005
embed_type:
  desc: null
  value: skill
embed_loss:
  desc: null
  value: decoder
embed_dim:
  desc: null
  value: 5
decoder_mask_type:
  desc: null
  value: ego
policy_mask_type:
  desc: null
  value: ego
epoch:
  desc: null
  value: 10000
init_epoch:
  desc: null
  value: 0
step_per_epoch:
  desc: null
  value: 50
max_num_trj:
  desc: null
  value: 100
max_trj_length:
  desc: null
  value: 1000
episode_len:
  desc: null
  value: 1000
episode_num:
  desc: null
  value: 2
eval_episodes:
  desc: null
  value: 3
rendering:
  desc: null
  value: true
visualize_latent_space:
  desc: null
  value: true
data_num:
  desc: null
  value: null
import_policy:
  desc: null
  value: false
gpu_idx:
  desc: null
  value: 0
verbose:
  desc: null
  value: true
device:
  desc: null
  value: cuda:0
obs_shape:
  desc: null
  value:
  - 39
action_shape:
  desc: null
  value:
  - 4
max_action:
  desc: null
  value: 1.0
masking_indices:
  desc: null
  value:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
decoder_masking_indices:
  desc: null
  value:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718564917
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      - 61
      4: 3.10.14
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
